name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: omkadu8767
          outputs: |
            assets/snake.svg?palette=github-dark

      - name: Commit and push snake
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/snake.svg
          if git diff --cached --quiet; then
            echo "No snake changes"
          else
            git commit -m "chore: update contribution snake"
            git push
          fi
